# Generated by Django 4.0.4 on 2022-05-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
