# Generated by Django 4.0.4 on 2022-05-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
